<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="0.004">
  <testcase classname="__main__.qa_openbci_py_i" name="test_001_t" time="0.0035">
    <error type="exceptions.ValueError">unable to coerce endpoint
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "qa_openbci_py_i.py", line 39, in test_001_t
    self.tb.connect(src, snk)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 131, in connect
    self._connect(points[i-1], points[i])
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 140, in _connect
    (src_block, src_port) = self._coerce_endpoint(src)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 152, in _coerce_endpoint
    raise ValueError("unable to coerce endpoint")
    </error>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
